{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "komtrol-service.fullname" . }}-secrets
  labels: {{- include "komtrol-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.storeName }}
    kind: SecretStore
  target:
    name: {{ include "komtrol-service.fullname" . }}-secrets
  data:
    {{- range .Values.secrets.keys }}
    - secretKey: {{ .envVar }}
      remoteRef:
        key: {{ .path }}
        property: {{ .property }}
    {{- end }}
{{- end }}
