apiVersion: v1
kind: Service
metadata:
  name: {{ include "komtrol-service.fullname" . }}
  labels: {{- include "komtrol-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "komtrol-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
