{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "komtrol-service.fullname" . }}
  labels: {{- include "komtrol-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "komtrol-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
